import re
import sqlite3

import pandas as pd

from csai_langchain.config.settings import (
    EBOS_DB,
)


class EBOSRepository:

    EVENT_COLUMN_PATTERN = re.compile(
        r"^BO(\d+)\s+(.+)$"
    )

    DATE_PRIORITY = (
        "Date Received",
        "PDF Date",
        "Date of Application",
        "Date of Data Recorded",
        "UpdatedAt",
    )

    OWNERSHIP_COLUMNS = (
        "Criteria A - Direct Ownership %",
        "Criteria B - Voting Shares %",
        "Direct Ownership %",
        "Indirect Ownership %",
        "Voting Shares %",
    )

    def __init__(self):

        self.db = EBOS_DB

    ####################################################
    # Normalize text
    ####################################################

    @staticmethod
    def normalize(
        value
    ):

        if (
            value is None
            or pd.isna(value)
        ):
            return ""

        value = str(
            value
        ).upper()

        value = re.sub(
            r"[^A-Z0-9\s]",
            " ",
            value
        )

        value = re.sub(
            r"\s+",
            " ",
            value
        )

        return value.strip()

    ####################################################
    # Parse date column
    ####################################################

    @staticmethod
    def parse_date_column(
        df,
        column
    ):

        if column not in df.columns:

            return pd.Series(
                pd.NaT,
                index=df.index,
                dtype="datetime64[ns]"
            )

        values = (
            df[column]
            .fillna("")
            .astype(str)
            .str.strip()
            .replace(
                {
                    "": pd.NA,
                    "NAN": pd.NA,
                    "NONE": pd.NA,
                    "-": pd.NA,
                }
            )
        )

        if column == "UpdatedAt":

            return pd.to_datetime(
                values,
                errors="coerce",
                dayfirst=False
            )

        return pd.to_datetime(
            values,
            errors="coerce",
            dayfirst=True
        )

    ####################################################
    # Convert percentage
    ####################################################

    @staticmethod
    def percentage_column(
        df,
        column
    ):

        if column not in df.columns:

            return pd.Series(
                0.0,
                index=df.index
            )

        values = (
            df[column]
            .fillna("")
            .astype(str)
            .str.replace(
                "%",
                "",
                regex=False
            )
            .str.replace(
                ",",
                "",
                regex=False
            )
            .str.strip()
        )

        return pd.to_numeric(
            values,
            errors="coerce"
        ).fillna(
            0.0
        )

    ####################################################
    # Read EBOS
    ####################################################

    def read_all(self):

        with sqlite3.connect(
            str(self.db)
        ) as conn:

            return pd.read_sql_query(
                "SELECT * FROM EBOS_Master",
                conn
            )

    ####################################################
    # Flatten numbered BO groups
    ####################################################

    @staticmethod
    def has_value(
        value
    ):

        return (
            value is not None
            and not pd.isna(value)
            and str(value).strip() != ""
        )

    def get_all_events(self):

        master = self.read_all()

        if master.empty:
            return master

        numbered_columns = {}

        for column in master.columns:

            match = self.EVENT_COLUMN_PATTERN.match(
                column
            )

            if not match:
                continue

            index = int(
                match.group(1)
            )
            field = match.group(2)

            numbered_columns.setdefault(
                index,
                {}
            )[field] = column

        # Backward compatibility for a database that has
        # not yet been regenerated by the wide extractor.
        if not numbered_columns:
            events = master.copy()
            events[
                "_master_company_name"
            ] = events.get(
                "Company Name"
            )
            events[
                "_master_company_no"
            ] = events.get(
                "Company No"
            )
            events[
                "_master_company"
            ] = events.get(
                "Client"
            )
            events[
                "_master_order"
            ] = range(
                len(events)
            )
            events[
                "_event_index"
            ] = range(
                1,
                len(events) + 1
            )

            return events

        events = []

        for master_order, row in master.iterrows():

            master_company_name = row.get(
                "Company Name"
            )
            master_company_no = row.get(
                "Company No"
            )

            for event_index in sorted(
                numbered_columns
            ):

                field_columns = numbered_columns[
                    event_index
                ]
                event = {
                    field: row.get(column)
                    for field, column
                    in field_columns.items()
                }

                if not any(
                    self.has_value(value)
                    for value in event.values()
                ):
                    continue

                event_company_name = event.get(
                    "Company Name"
                )
                event_company_no = event.get(
                    "Company No"
                )

                if not self.has_value(
                    event_company_name
                ):
                    event[
                        "Company Name"
                    ] = master_company_name

                if not self.has_value(
                    event_company_no
                ):
                    event[
                        "Company No"
                    ] = master_company_no

                event[
                    "_master_company_name"
                ] = master_company_name
                event[
                    "_master_company_no"
                ] = master_company_no
                event[
                    "_master_company"
                ] = row.get(
                    "Company"
                )
                event[
                    "_master_order"
                ] = master_order
                event[
                    "_event_index"
                ] = event_index

                if "UpdatedAt" in master.columns:
                    event["UpdatedAt"] = row.get(
                        "UpdatedAt"
                    )

                events.append(
                    event
                )

        return pd.DataFrame(
            events
        )

    def get_all_person_names(self):

        events = self.get_all_events()

        if (
            events.empty
            or "Name" not in events.columns
        ):
            return []

        people = {}

        for value in events["Name"]:

            if not self.has_value(value):
                continue

            display_name = str(
                value
            ).strip()
            normalized_name = self.normalize(
                display_name
            )

            if (
                normalized_name
                and normalized_name not in people
            ):
                people[
                    normalized_name
                ] = display_name

        return list(
            people.values()
        )

    ####################################################
    # Match company
    ####################################################

    def match_company_rows(
        self,
        df,
        company_name
    ):

        target = self.normalize(
            company_name
        )

        if not target:
            return df.iloc[
                0:0
            ].copy()

        df = df.copy()

        df["_company_std"] = (
            df["Company Name"]
            .apply(
                self.normalize
            )
        )

        if "_master_company_name" in df.columns:

            df["_master_company_std"] = (
                df["_master_company_name"]
                .apply(
                    self.normalize
                )
            )

        else:

            df["_master_company_std"] = (
                df["_company_std"]
            )

        ################################################
        # Exact normalized match
        ################################################

        exact = df[
            (
                df["_company_std"]
                == target
            )
            |
            (
                df["_master_company_std"]
                == target
            )
        ].copy()

        if not exact.empty:
            return self.expand_company_matches(
                df,
                exact
            )

        ################################################
        # Partial match only when unambiguous
        ################################################

        partial = df[
            df["_company_std"].str.contains(
                target,
                case=False,
                regex=False,
                na=False
            )
            |
            df[
                "_master_company_std"
            ].str.contains(
                target,
                case=False,
                regex=False,
                na=False
            )
        ].copy()

        if partial.empty:
            return partial

        matched_companies = {
            self.normalize(
                row.get(
                    "_master_company_name"
                )
                or row.get(
                    "Company Name"
                )
            )
            for _, row in partial.iterrows()
        }

        if len(
            matched_companies
        ) != 1:

            return df.iloc[
                0:0
            ].copy()

        return self.expand_company_matches(
            df,
            partial
        )

    def expand_company_matches(
        self,
        dataframe,
        matches
    ):

        registration_column = (
            "_master_company_no"
            if "_master_company_no"
            in dataframe.columns
            else "Company No"
        )

        if registration_column in matches.columns:

            registrations = {
                str(value).strip()
                for value in matches[
                    registration_column
                ]
                if self.has_value(value)
            }

            if registrations:

                return dataframe[
                    dataframe[
                        registration_column
                    ]
                    .fillna("")
                    .astype(str)
                    .str.strip()
                    .isin(
                        registrations
                    )
                ].copy()

        return matches.copy()

    ####################################################
    # Current beneficial owners
    ####################################################

    def get_current_beneficial_owners(
        self,
        company_name
    ):

        df = self.get_all_events()

        if df.empty:
            return []

        if "Company Name" not in df.columns:
            return []

        df = self.match_company_rows(
            df,
            company_name
        )

        if df.empty:
            return []

        df = df.copy()

        ################################################
        # Remove completely duplicated EBOS rows
        ################################################

        duplicate_columns = [

            column

            for column in (
                "Company Name",
                "Submission No",
                "BO Status",
                "Name",
                "IC",
                "Direct Ownership %",
                "Voting Shares %",
                "Date Received",
                "PDF Date",
                "Date of Cessation",
            )

            if column in df.columns
        ]

        if duplicate_columns:

            df = df.drop_duplicates(
                subset=duplicate_columns,
                keep="last"
            )

        ################################################
        # Filing date
        ################################################

        filing_date = pd.Series(
            pd.NaT,
            index=df.index,
            dtype="datetime64[ns]"
        )

        for column in self.DATE_PRIORITY:

            parsed = self.parse_date_column(
                df,
                column
            )

            filing_date = (
                filing_date.fillna(
                    parsed
                )
            )

        df["_filing_date"] = (
            filing_date
        )

        # Missing dates are treated as the oldest records.
        df["_filing_sort"] = (
            df["_filing_date"]
            .fillna(
                pd.Timestamp(
                    "1900-01-01"
                )
            )
        )

        ################################################
        # Submission number
        ################################################

        if "Submission No" in df.columns:

            df["_submission_sort"] = (
                df["Submission No"]
                .fillna("")
                .astype(str)
                .str.strip()
                .str.upper()
            )

        else:

            df["_submission_sort"] = ""

        ################################################
        # Person identity
        ################################################

        if "IC" in df.columns:

            ic_values = (
                df["IC"]
                .fillna("")
                .astype(str)
                .str.strip()
            )

        else:

            ic_values = pd.Series(
                "",
                index=df.index
            )

        if "Name" in df.columns:

            name_values = (
                df["Name"]
                .apply(
                    self.normalize
                )
            )

        else:

            name_values = pd.Series(
                "",
                index=df.index
            )

        df["_identity"] = (
            ic_values.where(
                ic_values != "",
                name_values
            )
        )

        df = df[
            df["_identity"] != ""
        ].copy()

        if df.empty:
            return []

        ################################################
        # BO status
        ################################################

        if "BO Status" in df.columns:

            df["_status"] = (
                df["BO Status"]
                .fillna("")
                .astype(str)
                .str.strip()
                .str.upper()
            )

        else:

            df["_status"] = ""

        cessation_date = (
            self.parse_date_column(
                df,
                "Date of Cessation"
            )
        )

        df["_is_cessation"] = (
            df["_status"].eq(
                "CESSATION"
            )
            |
            (
                df["_status"].eq("")
                &
                cessation_date.notna()
            )
        )

        ################################################
        # Status priority
        ################################################

        # When NEW and CESSATION occur in the same filing
        # for the same person, NEW represents the replacement
        # active ownership record.
        df["_status_priority"] = 2

        df.loc[
            df["_is_cessation"],
            "_status_priority"
        ] = 1

        df.loc[
            df["_status"].eq("NEW"),
            "_status_priority"
        ] = 3

        ################################################
        # Ownership score
        ################################################

        ownership_values = []

        for column in self.OWNERSHIP_COLUMNS:

            ownership_values.append(
                self.percentage_column(
                    df,
                    column
                )
            )

        if ownership_values:

            ownership_frame = pd.concat(
                ownership_values,
                axis=1
            )

            df["_ownership_score"] = (
                ownership_frame.max(
                    axis=1
                )
            )

        else:

            df["_ownership_score"] = 0.0

        ################################################
        # Stable original row order
        ################################################

        df["_row_order"] = range(
            len(df)
        )

        ################################################
        # Select latest event for each person
        ################################################

        df = df.sort_values(
            by=[
                "_filing_sort",
                "_submission_sort",
                "_status_priority",
                "_ownership_score",
                "_row_order",
            ],
            ascending=[
                True,
                True,
                True,
                True,
                True,
            ]
        )

        latest = (
            df.groupby(
                "_identity",
                sort=False,
                dropna=False
            )
            .tail(1)
            .copy()
        )

        ################################################
        # Exclude persons whose latest event is cessation
        ################################################

        latest = latest[
            ~latest["_is_cessation"]
        ].copy()

        if latest.empty:
            return []

        ################################################
        # Remove helper columns
        ################################################

        helper_columns = [
            column

            for column in latest.columns

            if column.startswith("_")
        ]

        latest = latest.drop(
            columns=helper_columns,
            errors="ignore"
        )

        ################################################
        # Stable output ordering
        ################################################

        if "Name" in latest.columns:

            latest = latest.sort_values(
                "Name",
                na_position="last"
            )

        latest = (
            latest
            .astype(object)
            .where(
                pd.notna(latest),
                None
            )
        )

        return latest.to_dict(
            orient="records"
        )

    ####################################################
    # Person beneficial-ownership history
    ####################################################

    def get_person_beneficial_ownership_history(
        self,
        person_name
    ):

        target = self.normalize(
            person_name
        )

        if not target:
            return []

        events = self.get_all_events()

        if (
            events.empty
            or "Name" not in events.columns
        ):
            return []

        events = events.copy()
        events["_person_std"] = (
            events["Name"]
            .apply(
                self.normalize
            )
        )

        events = events[
            events["_person_std"]
            == target
        ].copy()

        if events.empty:
            return []

        filing_date = pd.Series(
            pd.NaT,
            index=events.index,
            dtype="datetime64[ns]"
        )

        for column in self.DATE_PRIORITY:

            filing_date = filing_date.fillna(
                self.parse_date_column(
                    events,
                    column
                )
            )

        events["_filing_date"] = filing_date
        events["_company_sort"] = (
            events[
                "_master_company_name"
            ]
            if "_master_company_name"
            in events.columns
            else events["Company Name"]
        ).apply(
            self.normalize
        )

        events = events.sort_values(
            by=[
                "_company_sort",
                "_filing_date",
                "_event_index",
            ],
            ascending=[
                True,
                False,
                True,
            ],
            na_position="last",
        )

        events = (
            events
            .astype(object)
            .where(
                pd.notna(events),
                None
            )
        )

        results = []

        for _, row in events.iterrows():

            master_company_name = row.get(
                "_master_company_name"
            )
            master_company_no = row.get(
                "_master_company_no"
            )

            results.append({
                "Company Name": (
                    master_company_name
                    if self.has_value(
                        master_company_name
                    )
                    else row.get(
                        "Company Name"
                    )
                ),
                "Filed Company Name": row.get(
                    "Company Name"
                ),
                "Company No": (
                    master_company_no
                    if self.has_value(
                        master_company_no
                    )
                    else row.get(
                        "Company No"
                    )
                ),
                "Source PDF": row.get(
                    "Source PDF"
                ),
                "PDF Date": row.get(
                    "PDF Date"
                ),
                "Submission No": row.get(
                    "Submission No"
                ),
                "Date Received": row.get(
                    "Date Received"
                ),
                "BO Status": row.get(
                    "BO Status"
                ),
                "Name": row.get(
                    "Name"
                ),
                "IC": row.get(
                    "IC"
                ),
                "Designation": row.get(
                    "Designation"
                ),
                "Direct Ownership %": row.get(
                    (
                        "Criteria A - "
                        "Direct Ownership %"
                    )
                ),
                "Voting Shares %": row.get(
                    (
                        "Criteria B - "
                        "Voting Shares %"
                    )
                ),
                "Date of Becoming BO": row.get(
                    "Date of Becoming BO"
                ),
                "Date of Cessation": row.get(
                    "Date of Cessation"
                ),
            })

        return results
